name: metadata-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - flask
  - sqlalchemy
  - gunicorn
  - geopandas
  - requests
  - flask-cors
  - redis-py
  - dask
  - fastparquet
  - toolz
  - xlrd
  - pip
  - pip:
      - git+https://github.com/cormorack/yodapy.git
