name: app-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - fastapi
  - uvicorn
  - pymongo
  - redis-py
  - nomkl
  - sqlalchemy
  - fsspec
  - s3fs>=0.5.2
  - gspread
  - gunicorn
  - uvicorn
  - geopandas
  - requests
  - dask
  - pyarrow
  - toolz
  - xlrd
  - loguru
  - prometheus-fastapi-instrumentator
  - pip=20
