name: app-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - fastapi
  - uvicorn
  - pymongo
  - redis-py
  - nomkl
  - sqlalchemy
  - fsspec
  - s3fs=2022.02.0
  - gspread
  - gunicorn
  - uvicorn
  - geopandas
  - requests
  - cryptography<38
  - dask
  - pyarrow
  - toolz
  - xlrd
  - loguru
  - zarr
  - prometheus-fastapi-instrumentator
