name: metadata-env
channels:
  - conda-forge
dependencies:
  - python=3.6
  - flask
  - sqlalchemy
  - gunicorn
  - geopandas
  - requests
  - flask-cors
  - dask
  - fastparquet
  - toolz
  - pip
  - pip:
    - git+https://github.com/cormorack/yodapy.git