# Default values for cava-media.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: cava-metadata
# fullnameOverride: cava-media
path: /metadata
service:
  targetPort: 80
  portName: http
  type: ClusterIP
  port: 80
  containerPort: 80
  servicePortName: http
image:
  repository: cormorack/cava-metadata
  tag: "set-by-chartpress"
  pullSecrets: []
  pullPolicy: Always
replicas: 1
resources: {}
env:
  - name: AWS_ACCESS_KEY_ID
    value: ""
  - name: AWS_SECRET_ACCESS_KEY
    value: ""
  - name: OOI_TOKEN
    value: ""
  - name: OOI_USERNAME
    value: ""
  - name: REDIS_HOST
    value: ""
  - name: REDIS_PORT
    value: ""
  - name: GOOGLE_SERVICE_JSON
    value: ""
  # === Gunicorn Settings ======
  # Since fsspec doesn't support uvloop, defaults to asyncio for now ...
  - name: WORKER_CLASS
    value: "uvicorn.workers.UvicornH11Worker"
  # Defaults to 1 worker per core so it can be scaled via multiple pods ...
  # Set scaling with replicas of this pod
  - name: WORKERS_PER_CORE
    value: "1"
  - name: WEB_CONCURRENCY
    value: "1"
  - name: MAX_WORKERS
    value: "1"
restartPolicy: Always
nodeSelector: {}
ingress:
  expose: false

  # If secure, must provide tls
  secure: false

  # Adds tls for domain certification
  # tls:
  #   certResolver: DEVELOPMENT
  tls: {}
