version: "3"
services:
  cava-metadata:
    build:
      context: ../../
      dockerfile: ./resources/docker/Dockerfile
    ports:
      - 80:80
    command: /start-reload.sh
    volumes:
      - ../../app:/app:consistent
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - LOOP=asyncio
      - HTTP=h11
    networks:
      - cava-network
    depends_on:
      - redis-service
  redis-service:
      image: bitnami/redis:latest
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      ports:
        - 6379:6379
      expose:
        - 6379
      networks:
        - cava-network
networks:
  cava-network: