version: "3"
services:
  cava-metadata:
    build:
      context: ../../
      dockerfile: ./resources/docker/Dockerfile
    ports:
      - 8080:80
    command: /start-reload.sh
    volumes:
      - ../../app:/app:consistent
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - LOOP=asyncio
      - HTTP=h11
    networks:
      - cava-network
networks:
  cava-network: